# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://blog.tolleiv.de
title: blog.tolleiv.de
subtitle: random findings from the life of a programmers
author: Tolleiv Nietsch
simple_search: https://www.google.com/search
description: "this is just about all sorts of web related work with a small factor of fanciness - it's about coding, typo3, its extensions and everything"
keywords: typo3, community, login, solutions, product, templavoila, people, groups, solution, varnish, robert, content, cache, really, found, seems, possible, pages, specific, board, search, avoid, right, vision, documents, proof, algorithms, group, values, internal, discussions, thing, assume, change, reasonable, public, actually, results, document, boost, deliver, error, problem, concept, function, setup, clear, logged, happy, personal, everyone, enable, first, setting, comments, response, quite, parts, genetic, queries, roadmaps, vectors, decisions, population, communication, cases, nodejs, especially, complex, anything, factor, members, large, conclusion, concepts, project, fields, related, query, looking, things, kasper, specific pages, official, meeting, entire, current, share, general, field, closed, event, setups, interested, support, words, documentation, irritation, newsgroups, daniel, straight, technical, state, final, value, compare, working, optimizations, gradient, github, position, result, expectations, check, small, example, methods, approach, developer, comes, question, wanted, searches, lists, addition, gerrit, others, sense, using, vector, based, product board 8221, find good solutions, boost factor values, to the conclusion, the typo3 project

# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
date_format: "ordinal"

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: /atom.xml
subscribe_email:
# RSS feeds can list your email address if you like
email:

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
root: /
permalink: /:year/:month/:title/
source: source
destination: public
plugins: plugins
code_dir: downloads/code
category_dir: blog/categories
markdown: rdiscount
rdiscount:
  extensions:
    - autolink
    - footnotes
    - smart
pygments: false # default python pygments have been replaced by pygments.rb

paginate: 10          # Posts per page on the blog index
pagination_dir: blog  # Directory base for pagination URLs eg. /blog/page/2/
recent_posts: 5       # Posts in the sidebar Recent Posts section
excerpt_link: "Read on &rarr;"  # "Continue reading" link text at the bottom of excerpted articles

titlecase: true       # Converts page and post titles to titlecase

# list each of the sidebar modules you want to include, in the order you want them to appear.
# To add custom asides, create files in /source/_includes/custom/asides/ and add them to the list like 'custom/asides/custom_aside_name.html'
default_asides: [asides/nav.html, asides/recent_posts.html, asides/github.html, asides/delicious.html, asides/pinboard.html, asides/googleplus.html]

# Each layout uses the default asides, but they can have their own asides instead. Simply uncomment the lines below
# and add an array with the asides you want to use.
# blog_index_asides:
# post_asides:
# page_asides:

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Github repositories
github_user: tolleiv
github_repo_count: 1
github_show_profile_link: true
github_skip_forks: true

# Twitter
twitter_user: tolleiv
twitter_tweet_button: true

# Google +1
google_plus_one: false
google_plus_one_size: medium

# Google Plus Profile
# Hidden: No visible button, just add author information to search results
googleplus_user:
googleplus_hidden: false

# Pinboard
pinboard_user:
pinboard_count: 3

# Delicious
delicious_user:
delicious_count: 3

# Disqus Comments
disqus_short_name: tolleiv
disqus_show_comment_count: true

# Google Analytics
google_analytics_tracking_id:

# Facebook Like
facebook_like: false

flattr_user: tolleiv
